#!/bin/bash

echo "🔧 Azure Service Principal Permissions Setup"
echo "=============================================="
echo ""
echo "To enable individual app creation for each customer, your Azure service principal needs additional permissions."
echo ""
echo "Required Permission:"
echo "  📋 Application.ReadWrite.All - Allows creating app registrations"
echo ""
echo "How to grant this permission:"
echo ""
echo "1. 🌐 Go to Azure Portal (portal.azure.com)"
echo "2. 🔍 Navigate to 'Azure Active Directory' > 'App registrations'"
echo "3. 📱 Find your M365 Assessment Framework app registration"
echo "4. 🔑 Go to 'API permissions'"
echo "5. ➕ Click 'Add a permission'"
echo "6. 📊 Select 'Microsoft Graph'"
echo "7. 🛡️  Select 'Application permissions'"
echo "8. 🔍 Search for 'Application.ReadWrite.All'"
echo "9. ✅ Check the box for 'Application.ReadWrite.All'"
echo "10. 💾 Click 'Add permissions'"
echo "11. ⚖️  Click 'Grant admin consent for [Your Tenant]' (IMPORTANT!)"
echo ""
echo "Alternative: PowerShell command (requires admin):"
echo "================================================="
echo ""
echo "# Replace YOUR_APP_ID with your actual service principal App ID"
echo "Connect-AzureAD"
echo "New-AzureADServiceAppRoleAssignment \\"
echo "  -ObjectId \$(Get-AzureADServicePrincipal -Filter \"appId eq 'YOUR_APP_ID'\").ObjectId \\"
echo "  -PrincipalId \$(Get-AzureADServicePrincipal -Filter \"appId eq 'YOUR_APP_ID'\").ObjectId \\"
echo "  -ResourceId \$(Get-AzureADServicePrincipal -Filter \"appId eq '00000003-0000-0000-c000-000000000000'\").ObjectId \\"
echo "  -Id 1bfefb4e-e0b5-418b-a88f-73c46d2cc8e9"
echo ""
echo "After granting permissions:"
echo "=========================="
echo "1. 🔄 The system will automatically create individual apps for each customer"
echo "2. 🎯 Each customer will get their own dedicated app registration"
echo "3. 🛡️  Better security isolation between customers"
echo "4. 🏷️  Apps will be tagged with customer information"
echo ""
echo "If you prefer to keep using the shared multi-tenant approach:"
echo "============================================================"
echo "Set environment variable: CREATE_INDIVIDUAL_APPS=false"
echo ""

# Check if we can determine the current app ID from environment
if [ -f "api/local.settings.json" ] && command -v jq &> /dev/null; then
    APP_ID=$(jq -r '.Values.AZURE_CLIENT_ID // empty' api/local.settings.json)
    if [ ! -z "$APP_ID" ] && [ "$APP_ID" != "your-service-principal-client-id" ]; then
        echo "🎯 Your current App ID appears to be: $APP_ID"
        echo "Use this in the PowerShell command above."
    fi
fi
