name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    timeout-minutes: 30
    environment: production
    
    env:
      NODE_VERSION: '18.x'
      APP_LOCATION: 'm365-security-assessment/m365-assessment-framework'
      API_LOCATION: 'm365-security-assessment/m365-assessment-framework/api'
      OUTPUT_LOCATION: 'build'
      CI: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false

      - name: Install Dependencies
        working-directory: ${{ env.APP_LOCATION }}
        run: |
          npm ci
          npm install tailwindcss-animate --no-save
          npm ls tailwindcss-animate || npm install tailwindcss-animate --save-dev
          # Make sure the package is definitely installed and available
          npm list tailwindcss-animate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'

      - name: Ensure .nvmrc in App Root
        run: echo "18" > ${{ env.APP_LOCATION }}/.nvmrc

      - name: Build Application
        working-directory: ${{ env.APP_LOCATION }}
        run: npm run build
        env:
          CI: false
          NODE_ENV: production
          REACT_APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build API
        if: success()
        working-directory: ${{ env.API_LOCATION }}
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build --if-present
          fi

      - name: List build output
        run: ls -l ${{ env.APP_LOCATION }}/build

      - name: Fetch Secrets from Azure Key Vault
        run: |
          echo "Fetching secrets from Azure Key Vault..."
          AZURE_CLIENT_ID=$(az keyvault secret show --vault-name ${{ secrets.AZURE_KEYVAULT_NAME }} --name AZURE-CLIENT-ID --query value -o tsv)
          AZURE_TENANT_ID=$(az keyvault secret show --vault-name ${{ secrets.AZURE_KEYVAULT_NAME }} --name AZURE-TENANT-ID --query value -o tsv)
          AZURE_SUBSCRIPTION_ID=$(az keyvault secret show --vault-name ${{ secrets.AZURE_KEYVAULT_NAME }} --name AZURE-SUBSCRIPTION-ID --query value -o tsv)
          AZURE_STATIC_WEB_APPS_API_TOKEN=$(az keyvault secret show --vault-name ${{ secrets.AZURE_KEYVAULT_NAME }} --name AZURE-STATIC-WEB-APPS-API-TOKEN --query value -o tsv)
          echo "Secrets fetched successfully."
        env:
          AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_POND_069956E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          skip_app_build: true
          node_version: "18"
        env:
          IS_STATIC_EXPORT: true
          NODE_ENV: production
          WEBSITE_NODE_DEFAULT_VERSION: "18"
          FUNCTIONS_WORKER_RUNTIME: "node"
          FUNCTIONS_EXTENSION_VERSION: "~4"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_POND_069956E03 }}
          action: "close"

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true