name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    env:
      NODE_VERSION: '16.x'
      APP_LOCATION: 'm365-assessment-framework'
      API_LOCATION: 'm365-assessment-framework/api'
      OUTPUT_LOCATION: 'build'
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'

      - name: Install Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Install Dependencies
        working-directory: ${{ env.APP_LOCATION }}
        run: npm ci

      - name: Build Application
        working-directory: ${{ env.APP_LOCATION }}
        run: npm run build
        env:
          CI: true
          REACT_APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build API
        working-directory: ${{ env.API_LOCATION }}
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build --if-present
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        id: deploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          skip_app_build: true
          skip_api_build: true
        env:
          IS_STATIC_EXPORT: true
          NODE_ENV: production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"