name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    timeout-minutes: 30
    environment: production
    
    env:
      NODE_VERSION: '16.x'
      APP_LOCATION: 'm365-security-assessment/m365-assessment-framework'
      API_LOCATION: 'm365-security-assessment/m365-assessment-framework/api'
      OUTPUT_LOCATION: 'build'
      CI: false
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'

      - name: Debug Directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "App location contents:"
          ls -la ${{ env.APP_LOCATION }}

      - name: Install Dependencies
        working-directory: ${{ env.APP_LOCATION }}
        run: |
          npm install -g npm@8.19.4
          npm ci --verbose

      - name: Build Application
        working-directory: ${{ env.APP_LOCATION }}
        run: |
          echo "Starting build process..."
          npm run build --verbose
          echo "Build process completed"
        env:
          CI: false
          NODE_OPTIONS: --max-old-space-size=4096
          REACT_APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build API
        working-directory: ${{ env.API_LOCATION }}
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build --if-present
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        id: deploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_POND_069956E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
        env:
          IS_STATIC_EXPORT: true
          NODE_ENV: production

      - name: Build Status Check
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "failure" ]; then
            echo "Deployment failed. Check the Azure Static Web Apps logs for more details."
            exit 1
          fi

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_POND_069956E03 }}
          action: "close"

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
