name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            m365-security-assessment/m365-assessment-framework/package-lock.json
            m365-security-assessment/m365-assessment-framework/api/package-lock.json
      
      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: m365-security-assessment/m365-assessment-framework
        run: npm ci
      
      # Install API dependencies
      - name: Install API dependencies
        working-directory: m365-security-assessment/m365-assessment-framework/api
        run: npm ci
      
      # Deploy to Azure Static Web Apps (force production deployment)
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_POND_069956E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "m365-security-assessment/m365-assessment-framework"
          api_location: "m365-security-assessment/m365-assessment-framework/api"
          output_location: "build"
          skip_app_build: false
          skip_api_build: false  # Let Azure SWA build the API to detect language properly
          api_build_command: "npm run build"
        env:
          NODE_VERSION: "20"
          WEBSITE_NODE_DEFAULT_VERSION: "20"
          FUNCTIONS_EXTENSION_VERSION: "~4"
          FUNCTIONS_WORKER_RUNTIME: "node"
          AZURE_FUNCTIONS_ENVIRONMENT: "production"
          FUNCTIONS_WORKER_RUNTIME_VERSION: "~20"
          REACT_APP_API_URL: "/api"
          REACT_APP_CLIENT_ID: "d1cc9e16-9194-4892-92c5-473c9f65dcb3"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_POND_069956E03 }}
          action: "close"